# Generated by Django 2.2.13 on 2022-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is test desciption akcmdkjnvkfdbni vnsfjnbgkn dk'),
            preserve_default=False,
        ),
    ]
