# Generated by Django 2.2.13 on 2022-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='https://4.imimg.com/data4/XV/FB/MY-29019126/women-fancy-leather-jacket-500x500.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
