# Generated by Django 2.2.13 on 2022-04-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220312_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
